name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: gradle.properties
          property: mod_version
          default: 0.0.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build full build
        run: ./gradlew build

      - name: Build full API jar
        run: ./gradlew apiJar

      - name: Build client-only build
        run: ./gradlew jarClient

      - name: Build client-only API jar
        run: ./gradlew apiJarClient

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/release-${{ steps.version.outputs.mod_version }}',
              sha: context.sha
            })

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: "release-${{ steps.version.outputs.mod_version }}"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header

      - name: Release artifacts
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: "build/libs/*.jar"
          name: "Release ${{ steps.version.outputs.mod_version }}"
          tag: "release-${{ steps.version.outputs.mod_version }}"
          body: "${{ steps.git-cliff.outputs.content }}"
          makeLatest: 'latest'
          skipIfReleaseExists: 'true'

